/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/prefectures': {
    /**
     * Your GET endpoint
     * @description 指定された都道府県に関する都道府県データを返します。
     */
    get: operations['get-prefectures']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    /**
     * Prefecture
     * @description 都道府県データ
     */
    Prefecture: {
      prefCode: number
      prefName: string
    }
  }
  responses: {
    /** @description Example response */
    GetPrefecturesResponse: {
      headers: {}
      content: {
        'application/json': {
          message: string
          result: components['schemas']['Prefecture'][]
        }
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type external = Record<string, never>

export interface operations {
  /**
   * Your GET endpoint
   * @description 指定された都道府県に関する都道府県データを返します。
   */
  'get-prefectures': {
    responses: {
      200: components['responses']['GetPrefecturesResponse']
    }
  }
}
